#!/bin/bash

MAJOR="0"
MINOR="2"
BUILD=`./build.version`
GITID=`git log | grep commit | head -n 1 | cut -d " " -f 2`
DATE=`date +%Y%m%d`
HOST=`hostname`

echo "(* This file is generated by version.sh *)"
echo "structure Version ="
echo "struct"
echo "   val major = \"${MAJOR}\""
echo "   val minor = \"${MINOR}\""
echo "   val build = \"${BUILD}\""
echo "   val gitId = \"${GITID}\""
echo "   val date = \"${DATE}\""
echo "   val hostname = \"${HOST}\""
echo "   fun getVersionString() = major ^ \".\" ^ minor ^ \".\" ^ build"
echo "end"


