all: set.sml table.sml symbol.sml

set.sml: set.k
	cp set.k set.sml

table.sml: table.k
	cp table.k table.sml

symbol.sml: symbol.k
	cp symbol.k symbol.sml

clean:
	rm -f set.sml table.sml symbol.sml
