all: 

clean:
	rm -f ast_datatype_unfold.sml ast_fun_curry.sml ast_app_apply.sml ast_parse_tree.sml type.sml ast_infix_apply.sml ast_match_compile.sml ast_typedec_eval.sml convert_parse_tree.sml typed_ast.sml 

