all: kil kulex kuruc kuyacc tests
	make -C kupeg
	make -C kulex
	make -C kuruc
	make -C kuyacc
	make -C tests

clean:
	make -C kupeg clean
	make -C kulex clean
	make -C kuruc clean
	make -C kuyacc clean
	make -C tests clean



